# Generated by Django 4.0.2 on 2022-02-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='agent',
        ),
    ]
